# Generated by Django 2.2 on 2021-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dp_code',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
